---
title: Comparison
output: pdf_document
---
```{r setup, include=F}
#classoption: landscape
rm(list = ls())
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
knitr::opts_chunk$set(fig.showtext = TRUE, dpi = 300)
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
```

```{r message=F}
library(ggplot2)
library(patchwork)
library(dplyr)
library(tidyr)
library(stringr)
library(tibble)
library(showtext)
font_add("lmroman", regular = "lmroman10-regular.otf")
colorblind_pallette <- c("#E69F00", "#56B4E9", "#009E73","#D55E00", "#CC79A7")
```

```{r}
models = c("TiDeTree", "SciPhy")
dynamics = c("distinct", "hierarchical")
dynamics_labels = c("trees with transitions to distinct cell types",
                    "trees with hierarchical cell type transitions")
dirs = c("~/Desktop/Part2/TiDe/distinct/analysisOutput/",
         "~/Desktop/Part2/TiDe/hierarchical/analysisOutput/",
         "~/Desktop/Part2/Typewriter/distinct/analysisOutput/",
         "~/Desktop/Part2/Typewriter/hierarchical/analysisOutput/")

# inferred parameters
parameters = c("treeHeight", "treeLength", "editRate", 
               "birthRate.t0", "birthRate.t1", "birthRate.t2", "birthRate.t3",
               "deathRate.t0", "deathRate.t1", "deathRate.t2", "deathRate.t3", 
               "migrationRate.t1", "migrationRate.t2", "migrationRate.t3")

parameter_labels = c("treeHeight" = "tree height", "treeLength" = "tree length", 
                     "editRate" = "editing rate", 
                     "birthRate.t0" = "birth rate (type 0)", "birthRate.t1" = "birth rate (type 1)",
                     "birthRate.t2" = "birth rate (type 2)", "birthRate.t3" = "birth rate (type 3)",
                     "deathRate.t0" = "death rate (type 0)", "deathRate.t1" = "death rate (type 1)", 
                     "deathRate.t2" = "death rate (type 2)", "deathRate.t3" = "death rate (type 3)",
                     "migrationRate.t1" = "migration rate (to type 1)", 
                     "migrationRate.t2" = "migration rate (to type 2)",
                     "migrationRate.t3" = "migration rate (to type 3)")
```


# Diversity in simulated barcodes

```{r fig.dim = c(12,4)}
simStatFiles = paste0(dirs, "simStats.Rdat")
simStats = lapply(simStatFiles, readRDS)

simStats[[1]] = simStats[[1]] %>% mutate(model = "TiDeTree", dynamic = "distinct")
simStats[[2]] = simStats[[2]] %>% mutate(model = "TiDeTree", dynamic = "hierarchical")
simStats[[3]] = simStats[[3]] %>% mutate(model = "SciPhy", dynamic = "distinct")
simStats[[4]] = simStats[[4]] %>% mutate(model = "SciPhy", dynamic = "hierarchical")

simStats = bind_rows(simStats)
  
simStats_summarized = full_join(
  simStats %>% 
    select(c(nEdited, barcodeDiv, model, dynamic)) %>% 
    group_by(model, dynamic) %>% 
    summarise_all(~ mean(.)) %>% 
    gather("statistic", "mean", c("nEdited", "barcodeDiv")), 
  simStats %>% 
    select(c(nEdited, barcodeDiv, model, dynamic)) %>% 
    group_by(model, dynamic) %>% 
    summarise_all(~ sd(.)) %>% 
    gather("statistic", "sd", c("nEdited", "barcodeDiv"))
  ) %>%
  mutate(statistic = as.factor(statistic),
         model = factor(model, levels = models), 
         dynamic = factor(dynamic, levels = dynamics))

p1 <- ggplot(simStats_summarized %>% filter(statistic == "nEdited"), 
       aes(x = model, y = mean, color = dynamic, group = dynamic)) +
  geom_pointrange(aes(ymin = mean - sd/2, ymax = mean + sd/2)) +
  geom_line() +
  ylim(c(0,20)) +
  geom_hline(yintercept = 20, linetype = "dotted") +
  scale_color_manual(values = colorblind_pallette, labels = dynamics_labels) +
  labs(x = "Editing model", y = "Number of edited targets or tapes", col = "") +
  theme_bw(base_family = "lmroman", base_size = 16)

p2 <- ggplot(simStats_summarized %>% filter(statistic == "barcodeDiv"), 
       aes(x = model, y = mean, color = dynamic, group = dynamic)) +
  geom_pointrange(aes(ymin = mean - sd/2, ymax = mean + sd/2)) +
  geom_line() +
  ylim(c(0,1)) +
  geom_hline(yintercept = 1, linetype = "dotted") +
  scale_color_manual(values = colorblind_pallette, labels = dynamics_labels) +
  labs(x = "Editing model", y = "Barcode diversity", col = "") +
  theme_bw(base_family = "lmroman", base_size = 16)

p1 + p2 + plot_layout(guides = "collect")
```

# Comparison of inference performance

```{r fig.dim = c(16,12)}
infPFiles = paste0(dirs, "infPerformance.Rdat")
infP = lapply(infPFiles, readRDS)

perf_metrics = c("coverage", "abs_error_rel", "bias_rel", "hpd_width_rel", "hpd_proportion")
perf_metrics_labels = c("Coverage", "Normalized absolute error", "Normalized bias", 
                        "Normalized HPD width", "HPD proportion")
ylim = list(c(0,1), c(0,5), c(-5,5), c(0,15), c(0,3))

perfDat = sapply(c(1:4), function(i) {
  bind_rows(infP[[i]], .id = "metric") 
  }, simplify = F, USE.NAMES = T)

perfDat[[1]] = perfDat[[1]] %>% mutate(model = "TiDeTree", dynamic = "distinct")
perfDat[[2]] = perfDat[[2]] %>% mutate(model = "TiDeTree", dynamic = "hierarchical")
perfDat[[3]] = perfDat[[3]] %>% mutate(model = "SciPhy", dynamic = "distinct")
perfDat[[4]] = perfDat[[4]] %>% mutate(model = "SciPhy", dynamic = "hierarchical")

perfDat = bind_rows(perfDat)

for (m in c(1:length(perf_metrics))) {
  df = perfDat %>% filter(metric == perf_metrics[m])
  
  stats = full_join(
    df %>% 
      group_by(model, dynamic) %>% 
      summarise(across(parameters, ~ mean(.))) %>% 
      gather("parameter", "mean", parameters), 
    df %>% 
      group_by(model, dynamic) %>% 
      summarise(across(parameters, ~ sd(.))) %>% 
      gather("parameter", "sd", parameters)
    ) %>%
    mutate(parameter = factor(parameter, levels = parameters), 
           model = factor(model, levels = models),
           dynamic = factor(dynamic, levels = dynamics))
  
  if (perf_metrics[m] == "coverage") {
    optimal = 1
  } else {
    optimal = 0
  }
  
  p <- ggplot(stats, aes(x = model, y = mean, color = dynamic, group = dynamic)) + 
    {if (perf_metrics[m] == "coverage") geom_point(size = 2)} + 
    {if (perf_metrics[m] != "coverage") geom_pointrange(aes(ymin = mean - sd/2, ymax = mean + sd/2), size = 0.4)} +
    geom_line() +
    ylim(ylim[[m]]) +
    geom_hline(yintercept = optimal, linetype = "dotted") +
    scale_color_manual(values = colorblind_pallette, labels = dynamics_labels) +
    labs(x = "Editing model", y = perf_metrics_labels[m]) +
    theme_bw(base_family = "lmroman", base_size = 16) + 
    theme(legend.position = "none") +
    facet_wrap(vars(parameter), labeller = as_labeller(parameter_labels), nrow = 4, ncol = 4)
  print(p)
}
```


# Comparison of tree inference

```{r fig.dim = c(12,4)}
hpdTreesFiles = paste0(dirs, "hpdTreesOutput.Rdat")
hpdTrees = lapply(hpdTreesFiles, readRDS)

hpdTrees[[1]] = hpdTrees[[1]] %>% mutate(model = "TiDeTree", dynamic = "distinct")
hpdTrees[[2]] = hpdTrees[[2]] %>% mutate(model = "TiDeTree", dynamic = "hierarchical")
hpdTrees[[3]] = hpdTrees[[3]] %>% mutate(model = "SciPhy", dynamic = "distinct")
hpdTrees[[4]] = hpdTrees[[4]] %>% mutate(model = "SciPhy", dynamic = "hierarchical")

hpdTrees = bind_rows(hpdTrees) %>% mutate(proportion = nTrees / nTotal)

 
# Tree recovery
hpdTrees_recovery = hpdTrees %>% 
  select(c(model, dynamic, recovery)) %>% 
  group_by(model, dynamic) %>% 
  summarise(recovery = sum(recovery) / n()) %>%
  mutate(model = factor(model, levels = models),
  dynamic = factor(dynamic, levels = dynamics))

p1 <- ggplot(hpdTrees_recovery, aes(x = model, y = recovery, color = dynamic, group = dynamic)) +
  geom_point(size = 2) +
  geom_line() +
  ylim(c(0,1)) +
  geom_hline(yintercept = 1, linetype = "dotted") +
  scale_color_manual(values = colorblind_pallette, labels = dynamics_labels) +
  labs(x = "Editing model", y = "Tree coverage", col = "") +
  theme_bw(base_family = "lmroman", base_size = 16) +
  theme(legend.position = "none")


# Relative size of 95% credible set
hpdTrees_size = hpdTrees %>%
  group_by(model, dynamic) %>%
  summarise(mean = mean(proportion), sd = sd(proportion)) %>%
  mutate(model = factor(model, levels = models),
         dynamic = factor(dynamic, levels = dynamics))

p2 <- ggplot(hpdTrees_size, aes(x = model, y = mean, color = dynamic, group = dynamic)) +
  geom_pointrange(aes(ymin = mean - sd/2, ymax = mean + sd/2), size = 0.4) +
  geom_line() +
  ylim(c(0,1)) +
  geom_hline(yintercept = 0, linetype = "dotted") +
  scale_color_manual(values = colorblind_pallette, labels = dynamics_labels) +
  labs(x = "Editing model", y = "Relative size of the 95% credible set", col = "") +
  theme_bw(base_family = "lmroman", base_size = 16) +
  theme(legend.position = "none")

p1 + p2 
```


## Similarity/ distance between MCC tree and true tree

```{r fig.dim = c(12,8)}
mccFiles = paste0(dirs, "mccOutput.Rdat")
mccOut = lapply(mccFiles, readRDS)
 
mccOut[[1]] = mccOut[[1]] %>% mutate(model = "TiDeTree", dynamic = "distinct")
mccOut[[2]] = mccOut[[2]] %>% mutate(model = "TiDeTree", dynamic = "hierarchical")
mccOut[[3]] = mccOut[[3]] %>% mutate(model = "SciPhy", dynamic = "distinct")
mccOut[[4]] = mccOut[[4]] %>% mutate(model = "SciPhy", dynamic = "hierarchical")

mccOut = bind_rows(mccOut) 
 
metrics = c("wRF", "Nye", "shPI", "prop_type_correct")
 
mcc_metrics = full_join(
  mccOut %>%
    group_by(model, dynamic) %>%
    summarise(across(metrics, ~ mean(.))) %>%
    gather("metric", "mean", metrics),
  mccOut %>%
    group_by(model, dynamic) %>%
    summarise(across(metrics, ~ sd(.))) %>%
    gather("metric", "sd", metrics),
  ) %>%
  mutate(metric = factor(metric, levels = metrics),
         model = factor(model, levels = models), 
         dynamic = factor(dynamic, levels = dynamics))

p1 <- ggplot(mcc_metrics %>% filter(metric == "wRF"),
       aes(x = model, y = mean, color = dynamic, group = dynamic)) +
  geom_pointrange(aes(ymin = mean - sd/2, ymax = mean + sd/2), size = 0.4) +
  geom_line() +
  ylim(c(0,1)) +
  geom_hline(yintercept = 0, linetype = "dotted") +
  scale_color_manual(values = colorblind_pallette, labels = dynamics_labels) +
  labs(x = "Editing model", y = "Weighted Robinson-Foulds distance") +
  theme_bw(base_family = "lmroman", base_size = 16) +
  theme(legend.position = "none")

p2 <- ggplot(mcc_metrics %>% filter(metric == "Nye"),
       aes(x = model, y = mean, color = dynamic, group = dynamic)) +
  geom_pointrange(aes(ymin = mean - sd/2, ymax = mean + sd/2), size = 0.4) +
  geom_line() +
  ylim(c(0,1)) +
  geom_hline(yintercept = 0, linetype = "dotted") +
  scale_color_manual(values = colorblind_pallette, labels = dynamics_labels) +
  labs(x = "Editing model", y = "Nye similarity") +
  theme_bw(base_family = "lmroman", base_size = 16) +
  theme(legend.position = "none")

p3 <- ggplot(mcc_metrics %>% filter(metric == "shPI"),
       aes(x = model, y = mean, color = dynamic, group = dynamic)) +
  geom_pointrange(aes(ymin = mean - sd/2, ymax = mean + sd/2), size = 0.4) +
  geom_line() +
  ylim(c(0,1)) +
  geom_hline(yintercept = 0, linetype = "dotted") +
  scale_color_manual(values = colorblind_pallette, labels = dynamics_labels) +
  labs(x = "Editing model", y = "Shared Phylogenetic Information") +
  theme_bw(base_family = "lmroman", base_size = 16) +
  theme(legend.position = "none")

p4 <- ggplot(mcc_metrics %>% filter(metric == "prop_type_correct"),
       aes(x = model, y = mean, color = dynamic, group = dynamic)) +
  geom_pointrange(aes(ymin = mean - sd/2, ymax = mean + sd/2), size = 0.4) +
  geom_line() +
  ylim(c(0,1)) +
  geom_hline(yintercept = 1, linetype = "dotted") +
  scale_color_manual(values = colorblind_pallette, labels = dynamics_labels) +
  labs(x = "Editing model", y = "Proportion of correct types\nat internal nodes") +
  theme_bw(base_family = "lmroman", base_size = 16) +
  theme(legend.position = "none")

(p1 + p2) / (p3 + p4)
```