---
title: "Typewriter - sequential"
output: pdf_document
---

```{r setup, include=F}
# Script for plotting the estimates and posterior distributions of the phylogenetic and phylodynamic parameters of cell development.
rm(list = ls())
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
knitr::opts_chunk$set(fig.dim = c(26,6), fig.showtext = TRUE, dpi = 300)
```

```{r message=F}
library(ggplot2)
library(dplyr)
library(tidyr)
library(stringr)
library(tibble)
library(showtext)
library(HDInterval)
font_add("lmroman", regular = "~/lmroman10-regular.otf")
code_dir = '~/Projects/celldev'
analysis_dir = '~/Projects/celldev_data/analysisOutput' # settings: TiDe, Typewriter baseline
```

```{r reference}
# trees
trees = c("tree_s", "tree_ss", "tree_sd", "tree_sds", "tree_bd")

tree_labels = c("tree_s" = "synchronous tree",
                "tree_ss" = "synchronous trees with sampling",
                "tree_sd" = "synchronous trees with cell death",
                "tree_sds" = "synchronous trees with cell death and sampling",
                "tree_bd" = "birth-death-sampling trees")

# inferred parameters
parameters = c("birthRate", "deathRate", "treeHeight", "treeLength", "editRate")

# true parameters
treeParams = read.csv(file.path(code_dir, 'homog/simulation_trees/tree_params.csv'))
editRate_true = 0.45 # 0.45 for Typewriter sequential, otherwise 0.05

# priors 
priors = list()
priors$editRate = c(hdi(qlnorm, 0.95, meanlog = -1, sdlog = 1), # meanlog = -1 for Typewriter sequential, otherwise -3
                    "median" = qlnorm(0.5, meanlog = -1, sdlog = 1))
priors$birthRate = c(hdi(qlnorm, 0.95, meanlog = -1.5, sdlog = 1),
                     "median" = qlnorm(0.5, meanlog = -1.5, sdlog = 1))
priors$deathRate = c(hdi(qexp, 0.95, rate = 25),
                     "median" = qexp(0.5, rate = 25))
```

```{r include=FALSE}
# Number of simulations with ESS > 200

# load posterior parameter estimates
infOutput = readRDS(file.path(analysis_dir, "infOutput.Rdat"))

# create table and filter valid simulations
infOutputDat = bind_rows(infOutput, .id = "tree")
infOutputDat = infOutputDat %>% 
  mutate(tree = factor(tree, levels = trees)) %>%
  filter(minESS > 200)
infOutputDat %>% group_by(tree) %>% summarise(validSim = n())
```

# Editing rate

```{r}
# EDIT RATE
# prior: ~LogNormal(-3,1) -> 5-95% percentiles [0.0096, 0.2579]
p1 <- ggplot(data = infOutputDat, aes(x = seed, y = editRate_median)) +  
  geom_point() + 
  geom_errorbar(aes(ymin = editRate_lower, ymax = editRate_upper), alpha = 0.5) + 
  geom_hline(yintercept = editRate_true, color = "darkorange") +
  geom_hline(yintercept = priors$editRate["median"], color = "cadetblue", linetype = "dashed") +
  geom_ribbon(aes(ymin = priors$editRate["lower"], ymax = priors$editRate["upper"]), 
                alpha = 0.1, fill = "cadetblue") +
  ylim(c(0, 2)) + #c(0, 1)) +
  theme_bw(base_family = "lmroman", base_size = 20) + 
  xlab("Simulation") + 
  ylab("Posterior editing rate") +
  facet_wrap(vars(tree), labeller = as_labeller(tree_labels), nrow = 1, ncol = 5)
p1
```

# Phylodynamic parameters

```{r}
# extract true phylodynamic parameters
phyloParams = treeParams %>% 
  mutate(tree = factor(str_remove(tree, "_[0-9]+"), levels = trees)) %>%
  select(tree, birthRate, deathRate) %>% 
  distinct() 

# BIRTH RATE
# prior: ~LogNormal(-1.5,1) -> 5-95% percentiles [0.0431, 1.1559]
p2 <- ggplot(data = infOutputDat, aes(x = seed, y = birthRate_median)) +  
  geom_point() + 
  geom_errorbar(aes(ymin = birthRate_lower, ymax = birthRate_upper), alpha = 0.5) +  
  geom_hline(data = phyloParams, aes(yintercept = birthRate), color = "darkorange") +
  geom_hline(yintercept = priors$birthRate["median"], color = "cadetblue", linetype = "dashed") +
  geom_ribbon(aes(ymin = priors$birthRate["lower"], ymax = priors$birthRate["upper"]), 
              alpha = 0.1, fill = "cadetblue") +
  ylim(c(0, 1.5)) +
  theme_bw(base_family = "lmroman", base_size = 20) + 
  xlab("Simulation") + 
  ylab("Posterior birth rate") + 
  facet_wrap(vars(tree), labeller = as_labeller(tree_labels), nrow = 1, ncol = 5)
p2
```


```{r}
# DEATH RATE
# prior: ~Exp(25) -> 5-95% percentiles [0.0021, 0.1198]
p3 <- ggplot(data = infOutputDat, aes(x = seed, y = deathRate_median)) +  
  geom_point() + 
  geom_errorbar(aes(ymin = deathRate_lower, ymax = deathRate_upper), alpha = 0.5) +  
  geom_hline(data = phyloParams, aes(yintercept = deathRate), color = "darkorange") +
  geom_hline(yintercept = priors$deathRate["median"], color = "cadetblue", linetype = "dashed") +
  geom_ribbon(aes(ymin = priors$deathRate["lower"], ymax = priors$deathRate["upper"]), 
              alpha = 0.1, fill = "cadetblue") +
  ylim(c(0, 0.2)) +
  theme_bw(base_family = "lmroman", base_size = 20) + 
  xlab("Simulation") + 
  ylab("Posterior death rate") +
  facet_wrap(vars(tree), labeller = as_labeller(tree_labels), nrow = 1, ncol = 5)
p3
```

# Tree parameters

```{r}
# extract true tree parameters
treestatParams = treeParams %>% 
  mutate(seed = as.numeric(str_extract(tree, "[0-9]+"))) %>%
  mutate(tree = factor(str_remove(tree, "_[0-9]+"), levels = trees)) %>%
  select(tree, seed, treeHeight, treeLength) 

# TREE LENGTH
p4 <- ggplot(data = infOutputDat, aes(x = seed, y = treeLength_median)) +  
  geom_point() + 
  geom_errorbar(aes(ymin = treeLength_lower, ymax = treeLength_upper), alpha = 0.5) +  #crossbar
  geom_line(data = treestatParams, aes(x=seed, y=treeLength), color = "darkorange") +
  ylim(c(0, 5000)) +
  theme_bw(base_family = "lmroman", base_size = 20) + 
  xlab("Simulation") + 
  ylab("Posterior tree length") +
  facet_wrap(vars(tree), labeller = as_labeller(tree_labels), nrow = 1, ncol = 5)
p4
```


```{r}
# TREE HEIGHT
p5 <- ggplot(data = infOutputDat, aes(x = seed, y = treeHeight_median)) +  
  geom_point() + 
  geom_errorbar(aes(ymin = treeHeight_lower, ymax = treeHeight_upper), alpha = 0.5) +  #crossbar
    geom_line(data = treestatParams, aes(x = seed, y = treeHeight), color = "darkorange") +
  ylim(c(0, 41)) +
  theme_bw(base_family = "lmroman", base_size = 20) + 
  xlab("Simulation") + 
  ylab("Posterior tree height") +
  facet_wrap(vars(tree), labeller = as_labeller(tree_labels), nrow = 1, ncol = 5)
p5
```

